name: hs-monitor
version: 0.1.0.0
#synopsis:
#description:
license: BSD3
author: Daniel Liland
#category:
extra-source-files:
  - README.md

default-extensions:
  - OverloadedStrings
  - ImportQualifiedPost

dependencies:
  - base >= 4.7 && < 5
  - data-default
  - lens
  - monomer
  - text
  - text-show
  - directory
  - typed-process
  - MissingH
  - bytestring
  - strict
  - async
  - parallel-io

executables:
  hs-monitor:
    source-dirs: src
    main: Main.hs
    ghc-options:
      - -fwarn-incomplete-patterns
      - -threaded
